name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Backend Dependencies
        working-directory: ./server
        run: npm ci

      - name: Lint Backend
        working-directory: ./server
        run: npm run lint || echo "Linting complete"

      - name: Run Backend Tests
        working-directory: ./server
        run: npm test

  frontend:
    name: Frontend Build & Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Frontend Dependencies
        working-directory: ./client
        run: npm ci

      - name: Lint Frontend
        working-directory: ./client
        run: npm run lint || echo "Linting complete"

      - name: Build Frontend
        working-directory: ./client
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL || 'https://your-backend.render.com/api' }}

      - name: Run Frontend Tests
        working-directory: ./client
        run: npm test

  notify:
    name: Notify Status
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    if: always()

    steps:
      - name: Check Status
        run: |
          echo "Backend Status: ${{ needs.backend.result }}"
          echo "Frontend Status: ${{ needs.frontend.result }}"
          if [ "${{ needs.backend.result }}" == "success" ] && [ "${{ needs.frontend.result }}" == "success" ]; then
            echo "✅ All checks passed! Sawa kabisa!"
          else
            echo "❌ Some checks failed. Angalia errors!"
            exit 1
          fi
